In [1]:
try:
    from pyscf import gto, dft
    print("Found pyscf")
except:
    print("Can't import, installing via pip")
    !pip3 install pyscf
    from pyscf import gto

try:
    import numpy as np
    print("Found numpy")
except:
    print("Can't import, installing via pip")
    !pip3 install numpy
    import numpy as np

try:
    import matplotlib.pyplot as plt
    print("Found matplotlib")
except:
    print("Can't import, installing via pip")
    !pip3 install matplotlib
    import matplotlib.pyplot as plt

try:
    from ase import Atoms
    from ase.build import molecule
    from ase.visualize import view
    from ase.io import write
    print("Found ase")
except:
    print("Can't import, installing via pip")
    !pip3 install ase
    from ase import Atoms    
    from ase.build import molecule
    from ase.visualize import view
    from ase.io import write

try:
    from pyscf.geomopt.geometric_solver import optimize
    print("Found geometry module")
except:
    print("Can't import, installing via pip")
    !pip3 install "pyscf[geomopt]"
    from pyscf.geomopt.geometric_solver import optimize

/usr/local/lib/python3.11/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


Found pyscf
Found numpy
Found matplotlib
Found ase
Found geometry module


In [2]:
def ase2pyscf():
    atomspyscf = []
    pos = atoms.get_positions()
    ele = atoms.get_chemical_symbols()
    numatoms = atoms.get_global_number_of_atoms()
    for atom in range(numatoms):
        elements = list(ele[atom])
        coords = np.ndarray.tolist(pos[atom])
        elencoord = elements + coords
        elencoordfix = ' '.join(map(str, elencoord))
        atomspyscf.append(elencoordfix)
    
    trueoutput = "; ".join(atomspyscf)
    
    return trueoutput

In [3]:
moleculename = 'H2O'
atoms = molecule(moleculename)
inputatoms = ase2pyscf()

In [4]:
mol = gto.Mole()
mol.build(atom = inputatoms,
          basis = 'ccpvdz', 
          spin = 0, 
          unit = 'angstrom')

#atom = inputatoms,
#atom = 'O 0.0 0.0 0.119262 ; H 0.0 0.763239 -0.477047 ; H 0.0 -0.763239 -0.477047',

In [5]:
mf_hf = dft.RKS(mol)
mf_hf.xc = 'pbe' # default
mf_hf = mf_hf.newton() # second-order algortihm
mf_hf.kernel()

converged SCF energy = -76.3339693175618


-76.33396931756181

In [6]:
conv_params = { # These are the default settings
    'convergence_energy': 1e-6,  # Eh
    'convergence_grms': 3e-4,    # Eh/Bohr
    'convergence_gmax': 4.5e-4,  # Eh/Bohr
    'convergence_drms': 1.2e-3,  # Angstrom
    'convergence_dmax': 1.8e-3,  # Angstrom
}

In [7]:
dft_energies = []
def cb(envs):
  mf_hf = envs["g_scanner"].base
  dft_energies.append(mf_hf.e_tot)

In [8]:
mol_eq = optimize(mf_hf, **conv_params, maxsteps=100, callback=cb)

geometric-optimize called with the following command line:
/usr/local/lib/python3.11/site-packages/ipykernel_launcher.py -f /Users/rhysbunting/Library/Jupyter/runtime/kernel-ceabb60f-b916-4b89-8bb8-3b89581e76a8.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              *******


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O   0.000000   0.000000   0.119262    0.000000  0.000000  0.000000
   H   0.000000   0.763239  -0.477047    0.000000  0.000000  0.000000
   H   0.000000  -0.763239  -0.477047    0.000000  0.000000  0.000000
converged SCF energy = -76.3339693175634
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 O     0.0000000000    -0.0000000000    -0.0128451579
1 H     0.0000000000    -0.0033285029     0.0064242025
2 H     0.0000000000     0.0033285029     0.0064242025
----------------------------------------------
cycle 1: E = -76.3339693176  dE = -76.334  norm(grad) = 0.0164224


Step    0 : Gradient = 9.482e-03/1.285e-02 (rms/max) Energy = -76.3339693176
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 1.60000e-01 5.36712e-01 5.36712e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.000000   0.000000   0.130655   -0.000000  0.000000  0.011393
   H  -0.000000   0.757893  -0.482795   -0.000000 -0.005346 -0.005748
   H  -0.000000  -0.757893  -0.482795   -0.000000  0.005346 -0.005748

WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.
converged SCF energy = -76.3341776907934
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 O     0.0000000000     0.0000000000    -0.0026412135
1 H     0.0000000000    -0.0009584248     0.0013215230
2 H    -0.0000000000     0.0009584248     0.0013215230
----------------------------------------------
cycle 2: E = -76.3341776908  dE = -0.000208373  norm(grad) = 0.00350799


Step    1 : Displace = 9.184e-03/1.143e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 2.025e-03/2.641e-03 (rms/max) E (change) = -76.3341776908 (-2.084e-04) Quality = 1.187
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 1.49220e-01 4.68101e-01 5.36712e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.000000  -0.000000   0.132990   -0.000000 -0.000000  0.002335
   H  -0.000000   0.757511  -0.483999   -0.000000 -0.000382 -0.001204
   H  -0.000000  -0.757511  -0.483999   -0.000000  0.000382 -0.001204

WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.
converged SCF energy = -76.3341859029953
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 O     0.0000000000    -0.0000000000    -0.0000155191
1 H    -0.0000000000     0.0000079482     0.0000086709
2 H     0.0000000000    -0.0000079482     0.0000086709
----------------------------------------------
cycle 3: E = -76.334185903  dE = -8.2122e-06  norm(grad) = 2.27499e-05


Step    2 : Displace = 1.697e-03/2.359e-03 (rms/max) Trust = 1.414e-01 (+) Grad = 1.313e-05/1.552e-05 (rms/max) E (change) = -76.3341859030 (-8.212e-06) Quality = 1.008
Hessian Eigenvalues: 4.99994e-02 5.00000e-02 5.00000e-02 ... 1.47181e-01 4.71107e-01 5.36712e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.000000  -0.000000   0.133007   -0.000000  0.000000  0.000017
   H  -0.000000   0.757469  -0.484036   -0.000000 -0.000041 -0.000038
   H  -0.000000  -0.757469  -0.484036   -0.000000  0.000041 -0.000038
converged SCF energy = -76.3341859044688
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 O     0.0000000000    -0.0000000000    -0.0000005211
1 H     0.0000000000    -0.0000016451     0.0000011698
2 H    -0.0000000000     0.0000016451     0.0000011698
----------------------------------------------
cycle 4: E = -76.3341859045  dE = -1.47351e-09  norm(grad) = 2.90188e-06


Step    3 : Displace = 4.243e-05/4.520e-05 (rms/max) Trust = 2.000e-01 (+) Grad = 1.675e-06/2.019e-06 (rms/max) E (change) = -76.3341859045 (-1.474e-09) Quality = 0.993
Hessian Eigenvalues: 4.99994e-02 5.00000e-02 5.00000e-02 ... 1.47181e-01 4.71107e-01 5.36712e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 3.027 seconds


In [9]:
print(mol_eq.elements)
print(mol_eq.atom_coords())

['O', 'H', 'H']
[[-7.29693162e-14 -7.01871121e-14  2.51346753e-01]
 [-4.50278015e-14  1.43140915e+00 -9.14695872e-01]
 [-4.39672069e-14 -1.43140915e+00 -9.14695872e-01]]


In [10]:
optmolecule = Atoms(mol_eq.elements, positions=mol_eq.atom_coords())

In [11]:
view(optmolecule, viewer='x3d')

In [12]:
print(dft_energies[-1])

-76.33418590446877


In [13]:
write(f'{dft_energies[-1] * 27.2114079527}-{moleculename}.xyz', optmolecule)